### ISSUE TITLE
ValueError: Unknown loss function: 'confidence_loss_distance'.

### ISSUE THREAD

**Issue by PabloExperimental** [dina-lab3D/NanoNet#7]
Hi I'm trying to use this model on Google Colab, without success.
```
#@title Clone NanoNet trained model 


%%bash

if [ ! -f NanoNetReady ]; then
  # install dependencies
  pip -q install biopython
  pip install py3Dmol

  # download model
  if [ ! -d "NanoNet/" ]; then
    git clone https://github.com/dina-lab3D/NanoNet --quiet
  fi
  touch NanoNetReady
fi
```
```
import tensorflow as tf

NanoNet = tf.keras.saving.load_model("/content/NanoNet/NanoNet")
```
Output:

```
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-6-c7190608a413>](https://localhost:8080/#) in <cell line: 3>()
      1 import tensorflow as tf
      2 
----> 3 NanoNet = tf.keras.saving.load_model("/content/NanoNet/NanoNet")

2 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/saving/legacy/serialization.py](https://localhost:8080/#) in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    535             obj = module_objects.get(object_name)
    536             if obj is None:
--> 537                 raise ValueError(
    538                     f"Unknown {printable_module_name}: '{object_name}'. "
    539                     "Please ensure you are using a "

ValueError: Unknown loss function: 'confidence_loss_distance'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
```

Do you know how to solve this?

**Comment by tomerco4** [comment]
Hi, 
To load the trained model you can use the following line: 

NanoNet = tf.keras.models.load_model(nanonet_path, compile=False) 

Please let me know if this helps,
Tomer.

**Comment by PabloExperimental** [comment]
Thanks for helping! I picked a sequence from 'small_fasta.fa'
```
import numpy as np

def one_hot_encoding(sequence, max_len_sequence, alphabet):

  x_embed = np.zeros((max_len_sequence, len(alphabet)))

  for index_seq, amino in enumerate(sequence):
    index_amino = alphabet.index(amino)
    x_embed[index_seq][index_amino] = 1.0

  return x_embed

max_len_sequence = 140
alphabet = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P',
            'Q', 'R', 'S', 'T', 'V', 'W', 'Y', 'X', 'B']
print("Alphabet len:", len(alphabet))

# >7168_4th_CoV2_BL_308245-2
sequence = "VQLVESGGGLVQPGGSLRLSCVASGSGFESNAMGWYRQAPGKQRELVAGITSGGNTNYAESVKGRFTISRDNAKNTIYLQMNSLKPEDTAVYYCNAVGPRINPRGSPTNYWGQGTQVTVS"

x_pred = one_hot_encoding(sequence, max_len_sequence, alphabet)
result = NanoNet.predict(x_pred)
```
Now this is the problem:
```
Alphabet len: 22
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-28-7667b9725759>](https://localhost:8080/#) in <cell line: 22>()
     20 
     21 x_pred = one_hot_encoding(sequence, max_len_sequence, alphabet)
---> 22 result = NanoNet.predict(x_pred)

1 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py](https://localhost:8080/#) in tf__predict_function(iterator)
     13                 try:
     14                     do_return = True
---> 15                     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16                 except:
     17                     do_return = False

ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2440, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2425, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2413, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py", line 2381, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.10/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/src/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "NanoNet2" is incompatible with the layer: expected shape=(None, 140, 22), found shape=(None, 22)
```

**Comment by tomerco4** [comment]
Hi,
In tensorflow, you must give the input for the predict function with a batch dimension as well (even if you are predicting for a single input...).

To solve this in your code, the easiest way is  change the following line:

result = NanoNet.predict(x_pred)

To this line:

result = NanoNet.predict(tf.expand_dims(x_pred, axis=0))

Hope this helps,
Tomer.

**Comment by PabloExperimental** [comment]
It works! Thanks
